-- -- FEureka seed data

-- USE feureka;

-- -- Predefined categories for found_items and missing_reports
-- INSERT INTO categories (category_id, category_name) VALUES
--     (1, 'Electronics'),
--     (2, 'Documents & IDs'),
--     (3, 'Wallets & Purses'),
--     (4, 'Keys'),
--     (5, 'Clothing'),
--     (6, 'Bags'),
--     (7, 'Accessories'),
--     (8, 'School Supplies'),
--     (9, 'Personal Items'),
--     (10, 'Others');

-- -- Registered users
-- -- Passwords for local testing:
-- -- Mark Andaya (Admin): Admin1@123
-- -- Celina Espinola: Student1@123
-- -- Syril Celis: Student2@123
-- -- Sofia Cruz: Student3@123
-- -- Mark Dela Cruz: Staff1@123
-- INSERT INTO users (
--     user_id,
--     first_name,
--     last_name,
--     email,
--     password_hash,
--     role,
--     user_type,
--     year_level,
--     expiration_date
-- ) VALUES
--     (1, 'Mark', 'Andaya', 'mark.andaya.admin@fit.edu.ph', '$2y$10$aBXDHL4Z22XBEM0wBg/22eLes1po1QBh00IFWQmmmNy4Pea1fdUOq', 'Admin', NULL, NULL, NULL),
--     (2, 'Celina', 'Espinola', 'celina.espinola@fit.edu.ph', '$2y$12$yTb7dlmUrthX1qPbFyc5dekydS3phbgl0ZO2xBFgvxWAkLP3bcHve', 'User', 'Student', 1, '2030-06-30'),
--     (3, 'Syril', 'Celis', 'syril.celis@fit.edu.ph', '$2y$12$hLtF6.1lRsU7vfAYx0hQfO2t66fhDtaD6Vuk8aXnRk/afHXWU9oam', 'User', 'Student', 2, '2029-06-30'),
--     (4, 'Sofia', 'Cruz', 'sofia.cruz@fit.edu.ph', '$2y$12$xmQn2dtlsqYWgLUOKSstleXkARZlcf0WkIPIQkdUJ705uVPkeutT.', 'User', 'Student', 3, '2028-06-30'),
--     (5, 'Mark', 'Dela Cruz', 'mark.delacruz@fit.edu.ph', '$2y$10$yFVtSiuWtZUBxCivWHfZCukyL6MdNopFjgQDXduPzAkaA8ekejm.y', 'User', 'Staff', NULL, NULL);

-- -- Sample found items
INSERT INTO found_items (
    user_id,
    category_id,
    item_name,
    item_description,
    room,
    floor,
    location_description,
    date_found,
    status,
    image,
    processed_by,
    admin_notes
) VALUES
--     (
--         2,
--         1,
--         'Black Wireless Earbuds',
--         'Black wireless earbuds in a small charging case.',
--         'Room 402',
--         '4th Floor',
--         'Found on the teacher''s desk after the afternoon class.',
--         '2026-07-05',
--         'Pending',
--         'assets/uploads/found-black-wireless-earbuds.jpg',
--         NULL,
--         NULL
--     ),
--     (
--         3,
--         2,
--         'Student ID Lanyard',
--         'FEU student ID green lanyard',
--         'Library',
--         '14th Floor',
--         'Found near the computer area.',
--         '2026-07-03',
--         'Approved',
--         'assets/uploads/found-student-id-lanyard.jpg',
--         1,
--         'Approved for display after checking the submitted details.'
--     ),
--     (
--         4,
--         6,
--         'Navy Blue Backpack',
--         'Navy blue backpack with two notebooks inside.',
--         'Cafeteria',
--         'Ground Floor',
--         'Found under a table near the cashier area.',
--         '2026-06-29',
--         'Under Review',
--         'assets/uploads/found-navy-blue-backpack.jpg',
--         1,
--         'Possible owner advised to visit the Lost and Found Office for verification.'
--     ),
--     (
--         5,
--         4,
--         'Silver Key Ring With Red Tag',
--         'Small silver key ring with three keys and a red tag.',
--         'Room 605',
--         '6th Floor',
--         'Found beside the front row seats.',
--         '2026-06-18',
--         'Claimed',
--         'assets/uploads/found-silver-key-ring-with-red-tag.jpg',
--         1,
--         'Released after physical ownership verification at the Lost and Found Office.'
--     ),
--     (
--         5,
--         8,
--         'FX-991MS Scientific Calculator',
--         'Gray scientific calculator.',
--         'Room 1104',
--         '11th Floor',
--         'Reported from the back row of the classroom.',
--         '2026-06-24',
--         'Pending',
--         'assets/uploads/found-fx-991ms-scientific-calculator.jpg',
--         NULL,
--         NULL
--     );

-- -- Sample missing reports
-- INSERT INTO missing_reports (
--     user_id,
--     category_id,
--     item_name,
--     item_description,
--     room,
--     floor,
--     location_description,
--     date_lost,
--     contact_number,
--     status,
--     image,
--     processed_by,
--     admin_notes
-- ) VALUES
--     (
--         2,
--         1,
--         'Gray FX-991MS Scientific Calculator',
--         'Gray FX-991MS scientific calculator without calculator lid.',
--         'Room 1104',
--         '11th Floor',
--         'Last used during a morning class.',
--         '2026-07-02',
--         '0917-555-0101',
--         'Open',
--         NULL,
--         NULL,
--         NULL
--     ),
--     (
--         3,
--         3,
--         'Brown Wallet',
--         'Brown leather wallet containing school receipts.',
--         'Canteen',
--         '8th Floor',
--         'Possibly left on a dining table after lunch.',
--         '2026-06-27',
--         '0917-555-0102',
--         'Possible Match',
--         'assets/uploads/missing-brown-wallet.jpg',
--         1,
--         'Potential match found; owner should visit the Lost and Found Office.'
--     ),
--     (
--         5,
--         2,
--         'White Spiral Notebook',
--         'White spiral notebook with handwritten lecture notes.',
--         'iCare',
--         '14th Floor',
--         'Last seen at a cubicle desk',
--         '2026-06-20',
--         '0917-555-0103',
--         'Resolved',
--         'assets/uploads/missing-white-spiral-notebook.jpg',
--         1,
--         'Resolved after ownership was verified physically at the Lost and Found Office.'
--     );
        (
            2,
            1,
            'Logitech Black Wireless Mouse',
            'Black wireless computer mouse, Logitech brand, left at the student plaza seating area.',
            'N/A',
            '2nd Floor',
            'Student Plaza Seating Area',
            '2026-05-15',
            'Approved',
            'assets/uploads/found-logitech-black-wireless-mouse.jpg',
            1,
            'Approved after verifying the submitted report.'
        ),
        (
            3,
            2,
            'Brown Manila Envelope with Printed Handouts',
            'Brown manila envelope containing printed class handouts, found in hallway.',
            'Room 301',
            '3rd Floor',
            'Hallway outside Room 301',
            '2026-05-16',
            'Approved',
            'assets/uploads/found-manila-envelope-printed-handouts.jpg',
            1,
            'Approved following Lost and Found Office review.'
        ),
        (
            4,
            3,
            'Brown Bifold Leather Wallet',
            'Brown bifold leather wallet found on classroom front row seat.',
            'Room 401',
            '4th Floor',
            'Classroom Front Row',
            '2026-05-18',
            'Approved',
            'assets/uploads/found-brown-bifold-leather-wallet.jpg',
            1,
            'Verified and approved for public listing.'
        ),
        (
            5,
            4,
            'Silver House Key Set with Rubber Keychain',
            'Set of silver house keys attached to a rubber keychain.',
            'Room 501',
            '5th Floor',
            'Teacher''s Desk',
            '2026-05-19',
            'Approved',
            'assets/uploads/found-silver-house-key-rubber-keychain.jpg',
            1,
            'Approved after validating the reported information.'
        ),
        (
            2,
            5,
            'Blue Denim Jacket',
            'Blue denim jacket, casual fit, left near classroom entrance.',
            'Room 601',
            '6th Floor',
            'Near Classroom Entrance',
            '2026-05-21',
            'Approved',
            'assets/uploads/found-blue-denim-jacket.jpg',
            1,
            'Item details confirmed before publication.'
        ),
        (
            3,
            6,
            'Jansport Navy Blue Backpack',
            'Navy blue Jansport-style backpack found in the corridor.',
            'Room 701',
            '7th Floor',
            'Corridor outside Room 701',
            '2026-05-22',
            'Approved',
            'assets/uploads/found-jansport-navy-blue-backpack.jpg',
            1,
            'Approved after administrative review.'
        ),
        (
            4,
            7,
            'Black-Framed Prescription Eyeglasses',
            'Prescription eyeglasses with black plastic frame found at the canteen.',
            'N/A',
            '8th Floor',
            'Canteen Eating Area',
            '2026-05-23',
            'Approved',
            'assets/uploads/found-black-framed-prescription-eyeglasses.jpg',
            1,
            'Approved after cross-checking item details with the reporting staff.'
        ),
        (
            5,
            8,
            'Casio FX-991 Scientific Calculator',
            'Casio FX-991-series scientific calculator found near the water fountain.',
            'Room 901',
            '9th Floor',
            'Water Fountain',
            '2026-05-25',
            'Approved',
            'assets/uploads/found-casio-fx991-scientific-calculator.jpg',
            1,
            'Approved after verifying the submitted report.'
        ),
        (
            2,
            9,
            'Plastic Bento-Style Lunch Box',
            'Plastic bento-style lunch box left near restroom entrance.',
            'Room 1001',
            '10th Floor',
            'Restroom Entrance',
            '2026-05-26',
            'Approved',
            'assets/uploads/found-plastic-bento-lunch-box.jpg',
            1,
            'Approved following Lost and Found Office review.'
        ),
        (
            3,
            10,
            'Black Automatic Folding Umbrella',
            'Black automatic folding umbrella found in the study lounge.',
            'Room 1101',
            '11th Floor',
            'Study Lounge',
            '2026-05-28',
            'Approved',
            'assets/uploads/found-black-automatic-folding-umbrella.jpg',
            1,
            'Verified and approved for public listing.'
        ),
        (
            4,
            1,
            'Compact 60% Mechanical Keyboard',
            'Compact 60%-layout mechanical keyboard left in the computer laboratory.',
            'Room 1201',
            '12th Floor',
            'Computer Laboratory',
            '2026-05-29',
            'Approved',
            'assets/uploads/found-compact-mechanical-keyboard.jpg',
            1,
            'Approved after validating the reported information.'
        ),
        (
            5,
            2,
            'Printed Class Schedule Sheet',
            'Blank printed class schedule sheet found at the library reading area.',
            'Library',
            '14th Floor',
            'Library Reading Area',
            '2026-05-30',
            'Approved',
            'assets/uploads/found-printed-class-schedule-sheet.jpg',
            1,
            'Item details confirmed before publication.'
        ),
        (
            2,
            3,
            'Small Floral-Print Coin Purse',
            'Small coin purse with floral print design.',
            'N/A',
            '2nd Floor',
            'Student Plaza Seating Area',
            '2026-06-01',
            'Approved',
            'assets/uploads/found-floral-print-coin-purse.jpg',
            1,
            'Approved after administrative review.'
        ),
        (
            3,
            4,
            'Motorcycle Key with Rubber Grip',
            'Motorcycle ignition key with a rubber grip cover, found on classroom back row.',
            'Room 305',
            '3rd Floor',
            'Classroom Back Row',
            '2026-06-02',
            'Approved',
            'assets/uploads/found-motorcycle-key-rubber-grip.jpg',
            1,
            'Approved after cross-checking item details with the reporting staff.'
        ),
        (
            4,
            5,
            'Gray Pullover Hoodie',
            'Gray pullover hoodie, unbranded, left near the water fountain.',
            'Room 404',
            '4th Floor',
            'Water Fountain',
            '2026-06-03',
            'Approved',
            'assets/uploads/found-gray-pullover-hoodie.jpg',
            1,
            'Approved after verifying the submitted report.'
        ),
        (
            5,
            6,
            'Brown Canvas Messenger Bag',
            'Brown canvas messenger bag found in the study lounge.',
            'Room 505',
            '5th Floor',
            'Study Lounge',
            '2026-06-04',
            'Approved',
            'assets/uploads/found-brown-canvas-messenger-bag.jpg',
            1,
            'Approved following Lost and Found Office review.'
        ),
        (
            2,
            7,
            'Black Aviator Sunglasses',
            'Black-framed aviator-style sunglasses left on the teacher''s desk.',
            'Room 606',
            '6th Floor',
            'Teacher''s Desk',
            '2026-06-06',
            'Approved',
            'assets/uploads/found-black-aviator-sunglasses.jpg',
            1,
            'Verified and approved for public listing.'
        ),
        (
            3,
            8,
            'Spiral-Bound Notebook with Class Notes',
            'Spiral-bound notebook containing handwritten class notes, found on the front row.',
            'Room 707',
            '7th Floor',
            'Classroom Front Row',
            '2026-06-07',
            'Approved',
            'assets/uploads/found-spiral-bound-notebook-class-notes.jpg',
            1,
            'Approved after validating the reported information.'
        ),
        (
            4,
            9,
            'Stainless Steel Tumbler Water Bottle',
            'Stainless steel tumbler-style water bottle left at a canteen food stall.',
            'N/A',
            '8th Floor',
            'Canteen Food Stall',
            '2026-06-08',
            'Approved',
            'assets/uploads/found-stainless-steel-tumbler-bottle.jpg',
            1,
            'Item details confirmed before publication.'
        ),
        (
            5,
            10,
            'Foldable Aluminum Phone Stand',
            'Foldable aluminum phone stand found in the corridor.',
            'Room 908',
            '9th Floor',
            'Corridor outside Room 908',
            '2026-06-09',
            'Approved',
            'assets/uploads/found-foldable-aluminum-phone-stand.jpg',
            1,
            'Approved after administrative review.'
        ),
        (
            2,
            1,
            'Black 10000mAh Power Bank',
            'Black 10000mAh capacity power bank found near classroom entrance.',
            'Room 1009',
            '10th Floor',
            'Near Classroom Entrance',
            '2026-06-10',
            'Approved',
            'assets/uploads/found-black-10000mah-power-bank.jpg',
            1,
            'Approved after cross-checking item details with the reporting staff.'
        ),
        (
            3,
            2,
            'Unused Blue Book Exam Booklet',
            'Unused blue book exam booklet found in the hallway.',
            'Room 1110',
            '11th Floor',
            'Hallway outside Room 1110',
            '2026-06-11',
            'Approved',
            'assets/uploads/found-blue-book-exam-booklet.jpg',
            1,
            'Approved after verifying the submitted report.'
        ),
        (
            4,
            3,
            'Slim Brown Cardholder Wallet',
            'Slim brown cardholder wallet found outside the computer laboratory.',
            'Room 1211',
            '12th Floor',
            'Outside Computer Laboratory',
            '2026-06-12',
            'Approved',
            'assets/uploads/found-slim-brown-cardholder-wallet.jpg',
            1,
            'Approved following Lost and Found Office review.'
        ),
        (
            5,
            4,
            'Dormitory Room Key with Number Tag',
            'Dormitory room key attached to a numbered plastic tag, found at the iCARE reception area.',
            'iCARE',
            '14th Floor',
            'iCARE Reception Area',
            '2026-06-13',
            'Approved',
            'assets/uploads/found-dormitory-key-number-tag.jpg',
            1,
            'Verified and approved for public listing.'
        ),
        (
            2,
            5,
            'Navy Blue Baseball Cap',
            'Navy blue baseball cap left at the student plaza.',
            'N/A',
            '2nd Floor',
            'Student Plaza Seating Area',
            '2026-06-15',
            'Approved',
            'assets/uploads/found-navy-blue-baseball-cap.jpg',
            1,
            'Approved after validating the reported information.'
        ),
        (
            3,
            6,
            'Canvas Tote Bag with Print Design',
            'Canvas tote bag with a printed graphic design, found near the water fountain.',
            'Room 309',
            '3rd Floor',
            'Water Fountain',
            '2026-06-16',
            'Approved',
            'assets/uploads/found-canvas-tote-bag-print-design.jpg',
            1,
            'Item details confirmed before publication.'
        ),
        (
            4,
            7,
            'Casio Analog Wristwatch',
            'Casio-brand analog wristwatch with black rubber strap, found near the restroom entrance.',
            'Room 408',
            '4th Floor',
            'Restroom Entrance',
            '2026-06-17',
            'Approved',
            'assets/uploads/found-casio-analog-wristwatch.jpg',
            1,
            'Approved after administrative review.'
        ),
        (
            5,
            8,
            'Navy Blue Zippered Pencil Case',
            'Navy blue zippered pencil/ballpen case found on the classroom back row.',
            'Room 510',
            '5th Floor',
            'Classroom Back Row',
            '2026-06-18',
            'Approved',
            'assets/uploads/found-navy-blue-zippered-pencil-case.jpg',
            1,
            'Approved after cross-checking item details with the reporting staff.'
        ),
        (
            2,
            9,
            'Small Zippered Cosmetic Pouch',
            'Small zippered cosmetic pouch found in the corridor.',
            'Room 609',
            '6th Floor',
            'Corridor outside Room 609',
            '2026-06-19',
            'Approved',
            'assets/uploads/found-small-zippered-cosmetic-pouch.jpg',
            1,
            'Approved after verifying the submitted report.'
        ),
        (
            3,
            10,
            'Capacitive Tablet Stylus Pen',
            'Capacitive touchscreen stylus pen for tablets, found in the hallway.',
            'Room 705',
            '7th Floor',
            'Hallway outside Room 705',
            '2026-06-20',
            'Approved',
            'assets/uploads/found-capacitive-tablet-stylus-pen.jpg',
            1,
            'Approved following Lost and Found Office review.'
        ),
        (
            4,
            1,
            'Portable JBL-Style Bluetooth Speaker',
            'Portable cylindrical bluetooth speaker, JBL-style design, left at the canteen eating area.',
            'N/A',
            '8th Floor',
            'Canteen Eating Area',
            '2026-06-21',
            'Approved',
            'assets/uploads/found-jbl-style-bluetooth-speaker.jpg',
            1,
            'Verified and approved for public listing.'
        ),
        (
            5,
            2,
            'Pad of Blank Office Referral Slips',
            'Unused pad of blank office referral slips found on classroom front row.',
            'Room 903',
            '9th Floor',
            'Classroom Front Row',
            '2026-06-22',
            'Approved',
            'assets/uploads/found-blank-referral-slip-pad.jpg',
            1,
            'Approved after validating the reported information.'
        ),
        (
            2,
            3,
            'Canvas Fabric Wallet with Velcro Closure',
            'Canvas fabric wallet with velcro closure found on the teacher''s desk.',
            'Room 1004',
            '10th Floor',
            'Teacher''s Desk',
            '2026-06-23',
            'Approved',
            'assets/uploads/found-canvas-velcro-wallet.jpg',
            1,
            'Item details confirmed before publication.'
        ),
        (
            3,
            4,
            'Keychain with Small Charm Pendant',
            'Keychain with a small decorative charm pendant, found near classroom entrance.',
            'Room 1105',
            '11th Floor',
            'Near Classroom Entrance',
            '2026-06-24',
            'Approved',
            'assets/uploads/found-keychain-charm-pendant.jpg',
            1,
            'Approved after administrative review.'
        ),
        (
            4,
            5,
            'FEU Tech PE Uniform Polo Shirt',
            'FEU Tech physical education uniform polo shirt left on the classroom front row.',
            'Room 1206',
            '12th Floor',
            'Classroom Front Row',
            '2026-06-25',
            'Approved',
            'assets/uploads/found-feutech-pe-uniform-polo.jpg',
            1,
            'Approved after cross-checking item details with the reporting staff.'
        ),
        (
            5,
            6,
            'Nylon Drawstring Backpack',
            'Nylon drawstring-style backpack found in the library computer area.',
            'Library',
            '14th Floor',
            'Library Computer Area',
            '2026-06-26',
            'Approved',
            'assets/uploads/found-nylon-drawstring-backpack.jpg',
            1,
            'Approved after verifying the submitted report.'
        ),
        (
            2,
            7,
            'Decorative Claw Hair Clip',
            'Decorative claw-style hair clip found at the student plaza.',
            'N/A',
            '2nd Floor',
            'Student Plaza Seating Area',
            '2026-06-27',
            'Approved',
            'assets/uploads/found-decorative-claw-hair-clip.jpg',
            1,
            'Approved following Lost and Found Office review.'
        ),
        (
            3,
            8,
            'Set of Pastel Highlighters',
            'Set of pastel-colored highlighter pens found in the corridor.',
            'Room 312',
            '3rd Floor',
            'Corridor outside Room 312',
            '2026-06-28',
            'Approved',
            'assets/uploads/found-pastel-highlighter-set.jpg',
            1,
            'Verified and approved for public listing.'
        ),
        (
            4,
            9,
            'Small Bottle of Hand Sanitizer',
            'Small pocket-size bottle of hand sanitizer left in the study lounge.',
            'Room 411',
            '4th Floor',
            'Study Lounge',
            '2026-06-29',
            'Approved',
            'assets/uploads/found-pocket-hand-sanitizer-bottle.jpg',
            1,
            'Approved after validating the reported information.'
        ),
        (
            5,
            10,
            'Portable USB Mini Fan',
            'Portable USB-powered mini fan found near the water fountain.',
            'Room 507',
            '5th Floor',
            'Water Fountain',
            '2026-06-30',
            'Approved',
            'assets/uploads/found-portable-usb-mini-fan.jpg',
            1,
            'Item details confirmed before publication.'
        ),
        (
            2,
            1,
            'SanDisk 32GB USB Flash Drive',
            'SanDisk 32GB capacity USB flash drive found on the classroom back row.',
            'Room 604',
            '6th Floor',
            'Classroom Back Row',
            '2026-07-01',
            'Approved',
            'assets/uploads/found-sandisk-32gb-usb-flash-drive.jpg',
            1,
            'Approved after administrative review.'
        ),
        (
            3,
            2,
            'Stapled Course Reading Packet',
            'Stapled course reading packet found near the restroom entrance.',
            'Room 710',
            '7th Floor',
            'Restroom Entrance',
            '2026-07-02',
            'Approved',
            'assets/uploads/found-stapled-course-reading-packet.jpg',
            1,
            'Approved after cross-checking item details with the reporting staff.'
        ),
        (
            4,
            3,
            'Small Zippered Coin Purse',
            'Small zippered coin/zip purse left at a canteen food stall.',
            'N/A',
            '8th Floor',
            'Canteen Food Stall',
            '2026-07-03',
            'Approved',
            'assets/uploads/found-small-zippered-coin-purse.jpg',
            1,
            'Approved after verifying the submitted report.'
        ),
        (
            5,
            4,
            'Locker Key with Plastic Tag',
            'Locker key attached to a numbered plastic tag, found near the classroom entrance.',
            'Room 910',
            '9th Floor',
            'Near Classroom Entrance',
            '2026-07-04',
            'Approved',
            'assets/uploads/found-locker-key-plastic-tag.jpg',
            1,
            'Approved following Lost and Found Office review.'
        ),
        (
            2,
            5,
            'Yellow Disposable Rain Poncho',
            'Yellow disposable rain poncho found in the hallway.',
            'Room 1006',
            '10th Floor',
            'Hallway outside Room 1006',
            '2026-07-05',
            'Approved',
            'assets/uploads/found-yellow-disposable-rain-poncho.jpg',
            1,
            'Verified and approved for public listing.'
        ),
        (
            3,
            6,
            'Padded 13-Inch Laptop Sleeve',
            'Padded 13-inch laptop sleeve found in the corridor.',
            'Room 1108',
            '11th Floor',
            'Corridor outside Room 1108',
            '2026-07-06',
            'Approved',
            'assets/uploads/found-padded-13inch-laptop-sleeve.jpg',
            1,
            'Approved after validating the reported information.'
        ),
        (
            4,
            7,
            'Beaded Bracelet (Handmade Style)',
            'Handmade-style beaded bracelet found on the teacher''s desk.',
            'Room 1204',
            '12th Floor',
            'Teacher''s Desk',
            '2026-07-07',
            'Approved',
            'assets/uploads/found-handmade-beaded-bracelet.jpg',
            1,
            'Item details confirmed before publication.'
        ),
        (
            5,
            8,
            'Set of 12-Inch Plastic Rulers',
            'Set of 12-inch plastic rulers found outside the iCARE office.',
            'iCARE',
            '14th Floor',
            'Outside iCARE',
            '2026-07-08',
            'Approved',
            'assets/uploads/found-12inch-plastic-ruler-set.jpg',
            1,
            'Approved after administrative review.'
        ),
        (
            2,
            9,
            'Pouch of Travel-Size Tissue Packs',
            'Small pouch containing travel-size tissue packs, found at the student plaza seating area.',
            'N/A',
            '2nd Floor',
            'Student Plaza Seating Area',
            '2026-07-10',
            'Approved',
            'assets/uploads/found-travel-tissue-pack-pouch.jpg',
            1,
            'Approved after cross-checking item details with the reporting staff.'
        );